
DROP TABLE IF EXISTS movies;

CREATE TABLE movies (
  id LONG AUTO_INCREMENT  PRIMARY KEY,
  year INT NOT NULL,
  title VARCHAR(250) NOT NULL,
  studios VARCHAR(250) DEFAULT NULL,
  producers VARCHAR(250) DEFAULT NULL,
  winner VARCHAR(250) DEFAULT NULL
);

